// Regenerates the golden SysEx fixtures from the shared frame catalog.
//
// Run from the package root:
//
//   dart run tool/generate_golden_fixtures.dart
//
// Writes one `test/fixtures/<name>.syx` per entry in `goldenFrames()` plus a
// `test/fixtures/MANIFEST.md` describing each fixture's logical inputs and bytes
// so the firmware author can reproduce them. The golden test asserts the
// committed bytes match `PedalCodec.encodeFrame`, so this is only run when the
// protocol or catalog deliberately changes.
import 'dart:io';

import 'package:pedal_repository/pedal_repository.dart';

import '../test/helpers/golden_frames.dart';

void main() {
  final fixtures = goldenFrames();
  final dir = Directory('test/fixtures')..createSync(recursive: true);

  final manifest = StringBuffer()
    ..writeln('# Golden SysEx fixtures')
    ..writeln()
    ..writeln(
      'Generated by `tool/generate_golden_fixtures.dart` from the '
      '`goldenFrames()` catalog. Do not edit by hand. Each `.syx` is the exact '
      'byte stream `PedalCodec.encodeFrame` produces for the listed frame and '
      'the contract the firmware decodes.',
    )
    ..writeln();

  for (final entry in fixtures.entries) {
    final name = entry.key;
    final frame = entry.value;
    final bytes = PedalCodec.encodeFrame(frame);
    File('${dir.path}/$name.syx').writeAsBytesSync(bytes);

    final hex = bytes
        .map((b) => b.toRadixString(16).padLeft(2, '0').toUpperCase())
        .join(' ');
    manifest
      ..writeln('## `$name.syx`')
      ..writeln()
      ..writeln('- frame: `$frame`')
      ..writeln('- bytes (${bytes.length}): `$hex`')
      ..writeln();
  }

  File('${dir.path}/MANIFEST.md').writeAsStringSync(manifest.toString());

  stdout.writeln('Wrote ${fixtures.length} fixtures to ${dir.path}');
}
